trigger:
  - master

pr: none

pool:
  name: Hosted Ubuntu 1604
  demands: npm

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: custom
    verbose: false
    customCommand: ci
    customRegistry: useFeed
    customFeed: '445bf733-2596-4e3d-a319-a70892d2bea9'

- task: Npm@1
  displayName: 'npm versioning'
  inputs:
    command: custom
    verbose: false
    customCommand: 'version --no-git-tag-version 1.0.$(Build.BuildId)'

- task: Npm@1
  displayName: 'npm publish'
  inputs:
    command: publish
    verbose: false
    publishRegistry: useFeed
    publishFeed: '445bf733-2596-4e3d-a319-a70892d2bea9'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'
